import pygame

QUIT_GAME = pygame.USEREVENT + 1
MENU_STATE = pygame.USEREVENT + 2
PLAY_STATE = pygame.USEREVENT + 3
PAUSE_STATE = pygame.USEREVENT + 4
HIGHSCHORE_STATE = pygame.USEREVENT + 5
LOSE = pygame.USEREVENT + 6
SHOT_FIRED = pygame.USEREVENT + 7
FLEET_COLLISION = pygame.USEREVENT + 8
